docs/semesters/semesters-detail.swagger.ts, docs/semesters/semesters.swagger.ts, src/app.module.ts, src/semesters/controllers/semesters-detail.controller.ts, src/semesters/controllers/semesters.controller.ts, src/semesters/dtos/semesters-detail-response.dto.ts, src/semesters/dtos/semesters-info-response.dto.ts, src/semesters/dtos/semesters-leaders-response.dto.ts, src/semesters/dtos/semesters-list-response.dto.ts, src/semesters/dtos/semesters-members-response.dto.ts, src/semesters/dtos/semesters-parts-response.dto.ts, src/semesters/semesters.module.ts
nest를 첨 써봐서 이게 맞는지 모르겠네용 ㅎㅎ;
전반적인 네이밍, 필드 분리가 적합한지 봐주시면 좋을 것 같아요
=> docs: #5 역대 기수 전체 조회 및 기수별 연혁 조회 명세서 작성

src/main.ts
cors 에러로 인해 개발서버에서 프론트엔드 작업 불가. 
app.enableCors()를 통해 모든 origin에 대해 허용 
yarn run start:dev를 통해 서버가 정상적으로 실행되는지 확인. 
cors 에러가 해결이 되었는지는 서영이와 협의를 통해 테스트 완료. 
추후 배포 시 배포 도메인에 대한 origin allow로 변경해야할 필요가 있음. 
https://docs.nestjs.com/security/cors
=> hotfix : cors 에러 해결 

src/configs/typeorm.config.ts
하다가 typeorm config 설정이 잘못된 것 같아서 수정 요청드립니다! 
synchronize : true -> false로 변경
entities: [] -> [__dirname + "/../**/*.entity{.ts, .js}"] 로 변경
synchronize 옵션은 production database 에서 사용되면 안된다고 warning하고 있어 급하게 수정합니다. 
synchronize 옵션
https://docs.nestjs.com/techniques/database
https://orkhan.gitbook.io/typeorm/docs/faq#how-do-i-update-a-database-schema
=> hotfix : typeorm config 설정 변경 

docs/partners/partners.swagger.ts, src/partners/controllers/partners.controller.ts, src/partners/dtos/partners-response.dto.ts, src/partners/entities/partners.entity.ts, src/partners/partners.module.ts, src/partners/services/partners.service.ts
- #11 
- GET /partners API 개발 
- partners entity 생성
- partners service 생성 
- partners controller 수정 
- yarn run start:dev를 통해 서버를 실행합니다. 
- GET localhost:3000/partners 을 통해 partners 정보를 가져올 수 있는지 확인합니다. 
https://docs.nestjs.com/techniques/database
=> feat : GET /partners API 개발 

src/projects/services/projects.service.ts
=> hotfix: ProjectResponseDto members 항목 수정에 대한 긴급 수정

src/reviews/services/reviews.service.ts
한 기수의 사람이 2개 이상 아티클을 작성한 경우 정렬이 꼬이는 문제가 발생하였습니다
기수 순 정렬 후 이름순 / id 순 정렬 (id는 고유한 값이기에 문제 발생하지 않음)
=> FIX 아티클 중복 제거-1

src/aboutsopt/dtos/aboutsopt-response.dto.ts, src/aboutsopt/dtos/aboutsopt-update.dto.ts, src/aboutsopt/entities/aboutsopt.entity.ts
=> feat: add title field

src/aboutsopt/controllers/aboutsopt.controller.ts
=> refactor: api semester => generation으로모두 변경

src/projects/dtos/playground-member.ts, src/projects/services/project.service.ts
Team Leader라는 명칭이 요청사항에 존재하였으나 Main PM으로 통용되는 것으로 확인되어 제외하고 개발 진행했습니다
프로젝트 상세 탭에서 맴버의 역할에 대한 명칭이 수정되어 Enum에 반영하였어요
파트 이름에서 아래와 같이 명칭이 변경되었습니다
Team Leader
Main PM
PM
Team Improvement
디자이너
웹 프론트엔드 개발자
서버 개발자
iOS 개발자
Android 개발자
=> fix: member enum

src/projects/dtos/playground-member.ts
=> fix: add TL to member role

src/internal/playground/playground.repository.ts
=> fix: maxsize

src/projects/services/project.service.ts
=> fix: cacheable 제거

src/internal/playground/playground.repository.ts, src/projects/services/project.service.ts
=> chore add log

src/internal/playground/playground.repository.ts
=> chore: content size

src/internal/playground/playground.repository.ts, src/internal/playground/playground.service.ts, src/projects/controllers/projects.controller.ts, src/projects/services/project.service.ts
=> chore: remove console

src/internal/playground/playground.repository.ts, src/projects/services/project.service.ts
- decorator가 pgrepository에 달려있어야하는데  projectService에 달려있었어요.
-아래 계층으로 넘겼습니다
=> hotfix: Cacheable decorator

src/common/cache/cache.module.ts, src/internal/playground/playground.repository.ts
=> hotfix: pipe merge

.github/workflows/cd.develop.yml, .github/workflows/cd.prod.yml
=> refac: gitaction 수동 배포 추가

docs/clear-cache/clear-cache.swagger.ts, src/app.module.ts, src/clear-cache/clear-cache.module.ts, src/clear-cache/controller/clear-cache.controller.ts, src/clear-cache/dtos/clear-cache.dto.ts, src/clear-cache/service/clear-cache.service.ts
https://sopt-makers.slack.com/archives/C042T8GEA0Y/p1693637640068459
Swagger 혹은 API Call 을 통해 수동으로 캐시 초기화
=> 캐시 초기화 API 추가

src/sopticle/services/sopticle.service.ts
https://sopt32x3.slack.com/archives/C05NQA915KL/p1693751681136579
=> refac: sopticle 업로드 Fail Exception Logging 추가

src/sopticle/services/sopticle.service.ts
=> Sopticle Body Json Link Error Check

.github/workflows/cd.develop.yml, .github/workflows/cd.prod.yml, dockerfile
=> feat: Add deprecated docker image clear

dockerfile
=> feat: Docker Install Puppeteer package

src/aboutsopt/services/aboutsopt.service.ts, src/internal/crew/crew.repository.ts, src/internal/crew/crew.service.ts, src/study/service/study.service.ts
https://sopt-makers.slack.com/archives/C042T8GEA0Y/p1695256786154559
Crew Meeting API 기수 파라미터 추가
=> feat: Crew Meeting API generation param 추가 반영

docs/notification/notification.swagger.ts
=> fix: Swagger Docs 수정

.github/workflows/cd.develop.yml, dockerfile, src/configs/env.config.ts, src/scraper/scraper.service.ts
네이버 블로그 스크래퍼 배포 환경 테스트 완료
Local 과 다르게 Docker 환경에서 Puppeteer 모듈을 활용하기 위한 Prerequisite 작업이 필요
-> Docker File 수정
=> feat: 네이버 블로그 스크래퍼 작업 및 테스트 완료

docs/review/review.swagger.ts, migrations/1698048101283-migration.ts, src/configs/migration.config.ts, src/internal/playground/playground.service.ts, src/members/service/member.service.ts, src/reviews/controllers/reviews.controller.ts, src/reviews/dtos/reviews-response.dto.ts, src/reviews/entities/reviews.entity.ts, src/reviews/reviews.module.ts, src/reviews/services/reviews.service.ts, src/scraper/dto/create-scraper-response.dto.ts, src/scraper/dto/scrap-article.dto.ts, src/scraper/scraper.service.ts, src/sopticle/dtos/scrap-sopticle.dto.ts, src/sopticle/dtos/sopticle-response.dto.ts, src/sopticle/services/sopticle.service.ts
https://sopt-makers.slack.com/archives/C042T8GEA0Y/p1696862265748579
활동후기 페이지 개편
활동후기도 블로그에서 직접 스크랩하여 이미지를 띄워주는 방향으로 작업
활동리뷰 변경 작업목록 정리
DB Migration 코드 작성
Naver Blog Sopticle Title 처리
Description -> 전체 업데이트 API 개발
AuthorProfileImage 추가해야함 ->  전체 업데이트 API 개발
Dev 배포 작업
Dev 코드 배포
Dev Migration 실행
업데이트 API 실행
Test & QA
> Live 배포 작업 (클라이언트와 함께 진행)
Live 코드 배포
Live Migration 실행
업데이트 API 실행 -> 작업 용량이 큰 관계로 로컬에서 env 바꿔서 실행
=> 활동후기 리팩토링 작업

src/reviews/dtos/reviews-request.dto.ts, src/reviews/services/reviews.service.ts, src/sopticle/dtos/get-sopticle-list-request.dto.ts, src/sopticle/services/sopticle.service.ts
=> feat: Review and Sopticle Generation Query 작업

docs/projects/projects.swagger.ts, src/internal/playground/playground.service.ts, src/projects/controllers/projects.controller.ts, src/projects/dtos/get-projects-request.dto.ts, src/projects/services/project.service.ts
=> feat: WEB APP Filter Query 작업

src/scraper/scraper.service.ts
https://sopt-makers.slack.com/archives/C042T8GEA0Y/p1698278332415119
=> refac: Naver Blog Image Scraping 개선

src/internal/playground/dto/playground-project-response.dto.ts, src/internal/playground/playground.service.ts, src/projects/dtos/projects-response.dto.ts
https://sopt-makers.slack.com/archives/C042T8GEA0Y/p1698913254382799
프로젝트 탭 개선
=> feat: Get Projects Available, Founding Property

src/internal/playground/playground.service.ts
https://sopt-makers.slack.com/archives/C042T8GEA0Y/p1699273876269599
=> fix: project filtering error

.github/workflows/cd.develop.yml, .github/workflows/cd.prod.yml
=> fix: removing old dangling docker image before puliing

src/main.ts
=> refac: Admin Cors Error 설정 수정

package.json, src/app.module.ts, src/visitor/service/visitor.service.ts, yarn.lock
=> feat: Visitor Count Cache ttl Set, 자정 Visitor Count 초기화

docs/review/review.swagger.ts, src/reviews/controllers/reviews.controller.ts, src/reviews/dtos/reviews-request.dto.ts, src/reviews/entities/reviews.entity.ts, src/reviews/services/reviews.service.ts
https://sopt-makers.slack.com/archives/C042T8GEA0Y/p1709458787358749
활동후기에 필요한 데이터를 배열 형식으로 넣는 API 생성
=> 활동후기 삽입 API 생성

src/reviews/services/reviews.service.ts
=> refac: Put Review API 중복URL case 예외처리

docs/projects/projects.swagger.ts, src/projects/controllers/projects.controller.ts, src/projects/dtos/get-projects-request.dto.ts, src/projects/services/project.service.ts, src/utils/helper.ts
https://sopt-makers.slack.com/archives/C042T8GEA0Y/p1712304587544819
S3 요금 이슈로 인한 프로젝트 API 에 페이지네이션 추가
=> refac: Project API Pagination Add

docs/projects/projects.swagger.ts, src/projects/controllers/projects.controller.ts, src/projects/dtos/get-projects-request.dto.ts, src/projects/services/project.service.ts, src/reviews/services/reviews.service.ts, src/scraper/scraper.service.ts, src/utils/helper.ts
=> Project API Pagination 반영
